// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// astronomy_wrapper.cpp
double astro_make_time_(int year, int month, int day, int hour, int minute, double second);
extern "C" SEXP _astronomyengine_astro_make_time_(SEXP year, SEXP month, SEXP day, SEXP hour, SEXP minute, SEXP second) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_make_time_(cpp11::as_cpp<cpp11::decay_t<int>>(year), cpp11::as_cpp<cpp11::decay_t<int>>(month), cpp11::as_cpp<cpp11::decay_t<int>>(day), cpp11::as_cpp<cpp11::decay_t<int>>(hour), cpp11::as_cpp<cpp11::decay_t<int>>(minute), cpp11::as_cpp<cpp11::decay_t<double>>(second)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_current_time_();
extern "C" SEXP _astronomyengine_astro_current_time_() {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_current_time_());
  END_CPP11
}
// astronomy_wrapper.cpp
std::string astro_body_name_(int body);
extern "C" SEXP _astronomyengine_astro_body_name_(SEXP body) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_body_name_(cpp11::as_cpp<cpp11::decay_t<int>>(body)));
  END_CPP11
}
// astronomy_wrapper.cpp
int astro_body_code_(std::string name);
extern "C" SEXP _astronomyengine_astro_body_code_(SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_body_code_(cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_helio_vector_(int body, double time_posix);
extern "C" SEXP _astronomyengine_astro_helio_vector_(SEXP body, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_helio_vector_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_equator_(int body, double time_posix, double latitude, double longitude, double height, bool of_date, bool aberration);
extern "C" SEXP _astronomyengine_astro_equator_(SEXP body, SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height, SEXP of_date, SEXP aberration) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_equator_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<bool>>(of_date), cpp11::as_cpp<cpp11::decay_t<bool>>(aberration)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_sun_position_(double time_posix);
extern "C" SEXP _astronomyengine_astro_sun_position_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_sun_position_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_ecliptic_(double x, double y, double z, double time_posix);
extern "C" SEXP _astronomyengine_astro_ecliptic_(SEXP x, SEXP y, SEXP z, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_ecliptic_(cpp11::as_cpp<cpp11::decay_t<double>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_ecliptic_longitude_(int body, double time_posix);
extern "C" SEXP _astronomyengine_astro_ecliptic_longitude_(SEXP body, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_ecliptic_longitude_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_horizon_(double time_posix, double lat, double lon, double ra, double dec, int refraction);
extern "C" SEXP _astronomyengine_astro_horizon_(SEXP time_posix, SEXP lat, SEXP lon, SEXP ra, SEXP dec, SEXP refraction) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_horizon_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(lat), cpp11::as_cpp<cpp11::decay_t<double>>(lon), cpp11::as_cpp<cpp11::decay_t<double>>(ra), cpp11::as_cpp<cpp11::decay_t<double>>(dec), cpp11::as_cpp<cpp11::decay_t<int>>(refraction)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_pair_longitude_(int body1, int body2, double time_posix);
extern "C" SEXP _astronomyengine_astro_pair_longitude_(SEXP body1, SEXP body2, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_pair_longitude_(cpp11::as_cpp<cpp11::decay_t<int>>(body1), cpp11::as_cpp<cpp11::decay_t<int>>(body2), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_geo_vector_(int body, double time_posix, int aberration);
extern "C" SEXP _astronomyengine_astro_geo_vector_(SEXP body, SEXP time_posix, SEXP aberration) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_geo_vector_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<int>>(aberration)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_bary_state_(int body, double time_posix);
extern "C" SEXP _astronomyengine_astro_bary_state_(SEXP body, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_bary_state_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_observer_vector_(double time_posix, double latitude, double longitude, double height, bool of_date);
extern "C" SEXP _astronomyengine_astro_observer_vector_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height, SEXP of_date) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_observer_vector_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<bool>>(of_date)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_observer_state_(double time_posix, double latitude, double longitude, double height, bool of_date);
extern "C" SEXP _astronomyengine_astro_observer_state_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height, SEXP of_date) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_observer_state_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<bool>>(of_date)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_vector_observer_(list vector, bool of_date);
extern "C" SEXP _astronomyengine_astro_vector_observer_(SEXP vector, SEXP of_date) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_vector_observer_(cpp11::as_cpp<cpp11::decay_t<list>>(vector), cpp11::as_cpp<cpp11::decay_t<bool>>(of_date)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_observer_gravity_(double latitude, double height);
extern "C" SEXP _astronomyengine_astro_observer_gravity_(SEXP latitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_observer_gravity_(cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
SEXP astro_search_rise_set_ex_(int body, double latitude, double longitude, double height, double time_posix, int direction, double limit_days, double meters_above_ground);
extern "C" SEXP _astronomyengine_astro_search_rise_set_ex_(SEXP body, SEXP latitude, SEXP longitude, SEXP height, SEXP time_posix, SEXP direction, SEXP limit_days, SEXP meters_above_ground) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_rise_set_ex_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<int>>(direction), cpp11::as_cpp<cpp11::decay_t<double>>(limit_days), cpp11::as_cpp<cpp11::decay_t<double>>(meters_above_ground)));
  END_CPP11
}
// astronomy_wrapper.cpp
SEXP astro_search_altitude_(int body, double latitude, double longitude, double height, double time_posix, int direction, double limit_days, double altitude);
extern "C" SEXP _astronomyengine_astro_search_altitude_(SEXP body, SEXP latitude, SEXP longitude, SEXP height, SEXP time_posix, SEXP direction, SEXP limit_days, SEXP altitude) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_altitude_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<int>>(direction), cpp11::as_cpp<cpp11::decay_t<double>>(limit_days), cpp11::as_cpp<cpp11::decay_t<double>>(altitude)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_hour_angle_ex_(int body, double latitude, double longitude, double height, double hour_angle, double time_posix, int direction);
extern "C" SEXP _astronomyengine_astro_search_hour_angle_ex_(SEXP body, SEXP latitude, SEXP longitude, SEXP height, SEXP hour_angle, SEXP time_posix, SEXP direction) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_hour_angle_ex_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(hour_angle), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<int>>(direction)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_hour_angle_(int body, double latitude, double longitude, double height, double time_posix);
extern "C" SEXP _astronomyengine_astro_hour_angle_(SEXP body, SEXP latitude, SEXP longitude, SEXP height, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_hour_angle_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_moon_phase_(double time_posix);
extern "C" SEXP _astronomyengine_astro_moon_phase_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_moon_phase_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_search_moon_phase_(double target_lon, double start_time_posix, double limit_days);
extern "C" SEXP _astronomyengine_astro_search_moon_phase_(SEXP target_lon, SEXP start_time_posix, SEXP limit_days) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_moon_phase_(cpp11::as_cpp<cpp11::decay_t<double>>(target_lon), cpp11::as_cpp<cpp11::decay_t<double>>(start_time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(limit_days)));
  END_CPP11
}
// astronomy_wrapper.cpp
cpp11::list astro_search_moon_quarter_(double start_time_posix);
extern "C" SEXP _astronomyengine_astro_search_moon_quarter_(SEXP start_time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_moon_quarter_(cpp11::as_cpp<cpp11::decay_t<double>>(start_time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
cpp11::list astro_next_moon_quarter_(int quarter, double time_posix);
extern "C" SEXP _astronomyengine_astro_next_moon_quarter_(SEXP quarter, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_next_moon_quarter_(cpp11::as_cpp<cpp11::decay_t<int>>(quarter), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_lunar_eclipse_(double start_time_posix);
extern "C" SEXP _astronomyengine_astro_search_lunar_eclipse_(SEXP start_time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_lunar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(start_time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_next_lunar_eclipse_(double prev_eclipse_time_posix);
extern "C" SEXP _astronomyengine_astro_next_lunar_eclipse_(SEXP prev_eclipse_time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_next_lunar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(prev_eclipse_time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list search_global_solar_eclipse_(double start_time);
extern "C" SEXP _astronomyengine_search_global_solar_eclipse_(SEXP start_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(search_global_solar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(start_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
list next_global_solar_eclipse_(double prev_eclipse_time);
extern "C" SEXP _astronomyengine_next_global_solar_eclipse_(SEXP prev_eclipse_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(next_global_solar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(prev_eclipse_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
list search_local_solar_eclipse_(double start_time, double latitude, double longitude);
extern "C" SEXP _astronomyengine_search_local_solar_eclipse_(SEXP start_time, SEXP latitude, SEXP longitude) {
  BEGIN_CPP11
    return cpp11::as_sexp(search_local_solar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(start_time), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude)));
  END_CPP11
}
// astronomy_wrapper.cpp
list next_local_solar_eclipse_(double prev_eclipse_time, double latitude, double longitude);
extern "C" SEXP _astronomyengine_next_local_solar_eclipse_(SEXP prev_eclipse_time, SEXP latitude, SEXP longitude) {
  BEGIN_CPP11
    return cpp11::as_sexp(next_local_solar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(prev_eclipse_time), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_transit_(int body, double start_time_posix);
extern "C" SEXP _astronomyengine_astro_search_transit_(SEXP body, SEXP start_time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_transit_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(start_time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_next_transit_(int body, double prev_transit_time_posix);
extern "C" SEXP _astronomyengine_astro_next_transit_(SEXP body, SEXP prev_transit_time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_next_transit_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(prev_transit_time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list search_lunar_apsis_(double start_time);
extern "C" SEXP _astronomyengine_search_lunar_apsis_(SEXP start_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(search_lunar_apsis_(cpp11::as_cpp<cpp11::decay_t<double>>(start_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
list next_lunar_apsis_(list apsis_list);
extern "C" SEXP _astronomyengine_next_lunar_apsis_(SEXP apsis_list) {
  BEGIN_CPP11
    return cpp11::as_sexp(next_lunar_apsis_(cpp11::as_cpp<cpp11::decay_t<list>>(apsis_list)));
  END_CPP11
}
// astronomy_wrapper.cpp
list search_planet_apsis_(int body, doubles start_time);
extern "C" SEXP _astronomyengine_search_planet_apsis_(SEXP body, SEXP start_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(search_planet_apsis_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<doubles>>(start_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
list next_planet_apsis_(int body, list apsis_list);
extern "C" SEXP _astronomyengine_next_planet_apsis_(SEXP body, SEXP apsis_list) {
  BEGIN_CPP11
    return cpp11::as_sexp(next_planet_apsis_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<list>>(apsis_list)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_illumination_(int body, double time_posix);
extern "C" SEXP _astronomyengine_astro_illumination_(SEXP body, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_illumination_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_peak_magnitude_(int body, double start_time);
extern "C" SEXP _astronomyengine_astro_search_peak_magnitude_(SEXP body, SEXP start_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_peak_magnitude_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(start_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_angle_from_sun_(int body, double time);
extern "C" SEXP _astronomyengine_astro_angle_from_sun_(SEXP body, SEXP time) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_angle_from_sun_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_elongation_(int body, double time);
extern "C" SEXP _astronomyengine_astro_elongation_(SEXP body, SEXP time) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_elongation_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_max_elongation_(int body, double start_time);
extern "C" SEXP _astronomyengine_astro_search_max_elongation_(SEXP body, SEXP start_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_max_elongation_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(start_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_search_relative_longitude_(int body, double target_rel_lon, double start_time);
extern "C" SEXP _astronomyengine_astro_search_relative_longitude_(SEXP body, SEXP target_rel_lon, SEXP start_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_relative_longitude_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(target_rel_lon), cpp11::as_cpp<cpp11::decay_t<double>>(start_time)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_search_sun_longitude_(double target_lon, double start_time, double limit_days);
extern "C" SEXP _astronomyengine_astro_search_sun_longitude_(SEXP target_lon, SEXP start_time, SEXP limit_days) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_sun_longitude_(cpp11::as_cpp<cpp11::decay_t<double>>(target_lon), cpp11::as_cpp<cpp11::decay_t<double>>(start_time), cpp11::as_cpp<cpp11::decay_t<double>>(limit_days)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_seasons_(int year);
extern "C" SEXP _astronomyengine_astro_seasons_(SEXP year) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_seasons_(cpp11::as_cpp<cpp11::decay_t<int>>(year)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_lunar_apsis_(double time_posix);
extern "C" SEXP _astronomyengine_astro_search_lunar_apsis_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_lunar_apsis_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_constellation_(double ra, double dec);
extern "C" SEXP _astronomyengine_astro_constellation_(SEXP ra, SEXP dec) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_constellation_(cpp11::as_cpp<cpp11::decay_t<double>>(ra), cpp11::as_cpp<cpp11::decay_t<double>>(dec)));
  END_CPP11
}
// astronomy_wrapper.cpp
double astro_helio_distance_(int body, double time_posix);
extern "C" SEXP _astronomyengine_astro_helio_distance_(SEXP body, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_helio_distance_(cpp11::as_cpp<cpp11::decay_t<int>>(body), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_search_global_solar_eclipse_(double time_posix);
extern "C" SEXP _astronomyengine_astro_search_global_solar_eclipse_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_search_global_solar_eclipse_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_identity_matrix_();
extern "C" SEXP _astronomyengine_astro_identity_matrix_() {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_identity_matrix_());
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_inverse_rotation_(doubles rotation);
extern "C" SEXP _astronomyengine_astro_inverse_rotation_(SEXP rotation) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_inverse_rotation_(cpp11::as_cpp<cpp11::decay_t<doubles>>(rotation)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_combine_rotation_(doubles a, doubles b);
extern "C" SEXP _astronomyengine_astro_combine_rotation_(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_combine_rotation_(cpp11::as_cpp<cpp11::decay_t<doubles>>(a), cpp11::as_cpp<cpp11::decay_t<doubles>>(b)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_pivot_(doubles rotation, int axis, double angle);
extern "C" SEXP _astronomyengine_astro_pivot_(SEXP rotation, SEXP axis, SEXP angle) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_pivot_(cpp11::as_cpp<cpp11::decay_t<doubles>>(rotation), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<double>>(angle)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_rotate_vector_(doubles rotation, list vector);
extern "C" SEXP _astronomyengine_astro_rotate_vector_(SEXP rotation, SEXP vector) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotate_vector_(cpp11::as_cpp<cpp11::decay_t<doubles>>(rotation), cpp11::as_cpp<cpp11::decay_t<list>>(vector)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_vector_from_sphere_(list sphere, double time_posix);
extern "C" SEXP _astronomyengine_astro_vector_from_sphere_(SEXP sphere, SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_vector_from_sphere_(cpp11::as_cpp<cpp11::decay_t<list>>(sphere), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_sphere_from_vector_(list vector);
extern "C" SEXP _astronomyengine_astro_sphere_from_vector_(SEXP vector) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_sphere_from_vector_(cpp11::as_cpp<cpp11::decay_t<list>>(vector)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_equator_from_vector_(list vector);
extern "C" SEXP _astronomyengine_astro_equator_from_vector_(SEXP vector) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_equator_from_vector_(cpp11::as_cpp<cpp11::decay_t<list>>(vector)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_vector_from_horizon_(list sphere, double time_posix, int refraction);
extern "C" SEXP _astronomyengine_astro_vector_from_horizon_(SEXP sphere, SEXP time_posix, SEXP refraction) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_vector_from_horizon_(cpp11::as_cpp<cpp11::decay_t<list>>(sphere), cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<int>>(refraction)));
  END_CPP11
}
// astronomy_wrapper.cpp
list astro_horizon_from_vector_(list vector, int refraction);
extern "C" SEXP _astronomyengine_astro_horizon_from_vector_(SEXP vector, SEXP refraction) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_horizon_from_vector_(cpp11::as_cpp<cpp11::decay_t<list>>(vector), cpp11::as_cpp<cpp11::decay_t<int>>(refraction)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqd_eqj_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_eqd_eqj_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqd_eqj_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqd_ect_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_eqd_ect_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqd_ect_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqd_ecl_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_eqd_ecl_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqd_ecl_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqd_hor_(double time_posix, double latitude, double longitude, double height);
extern "C" SEXP _astronomyengine_astro_rotation_eqd_hor_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqd_hor_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqj_eqd_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_eqj_eqd_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqj_eqd_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqj_ect_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_eqj_ect_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqj_ect_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqj_ecl_();
extern "C" SEXP _astronomyengine_astro_rotation_eqj_ecl_() {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqj_ecl_());
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqj_hor_(double time_posix, double latitude, double longitude, double height);
extern "C" SEXP _astronomyengine_astro_rotation_eqj_hor_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqj_hor_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_ect_eqd_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_ect_eqd_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_ect_eqd_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_ect_eqj_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_ect_eqj_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_ect_eqj_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_ecl_eqd_(double time_posix);
extern "C" SEXP _astronomyengine_astro_rotation_ecl_eqd_(SEXP time_posix) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_ecl_eqd_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_ecl_eqj_();
extern "C" SEXP _astronomyengine_astro_rotation_ecl_eqj_() {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_ecl_eqj_());
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_ecl_hor_(double time_posix, double latitude, double longitude, double height);
extern "C" SEXP _astronomyengine_astro_rotation_ecl_hor_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_ecl_hor_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_hor_eqd_(double time_posix, double latitude, double longitude, double height);
extern "C" SEXP _astronomyengine_astro_rotation_hor_eqd_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_hor_eqd_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_hor_eqj_(double time_posix, double latitude, double longitude, double height);
extern "C" SEXP _astronomyengine_astro_rotation_hor_eqj_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_hor_eqj_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_hor_ecl_(double time_posix, double latitude, double longitude, double height);
extern "C" SEXP _astronomyengine_astro_rotation_hor_ecl_(SEXP time_posix, SEXP latitude, SEXP longitude, SEXP height) {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_hor_ecl_(cpp11::as_cpp<cpp11::decay_t<double>>(time_posix), cpp11::as_cpp<cpp11::decay_t<double>>(latitude), cpp11::as_cpp<cpp11::decay_t<double>>(longitude), cpp11::as_cpp<cpp11::decay_t<double>>(height)));
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_eqj_gal_();
extern "C" SEXP _astronomyengine_astro_rotation_eqj_gal_() {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_eqj_gal_());
  END_CPP11
}
// astronomy_wrapper.cpp
doubles astro_rotation_gal_eqj_();
extern "C" SEXP _astronomyengine_astro_rotation_gal_eqj_() {
  BEGIN_CPP11
    return cpp11::as_sexp(astro_rotation_gal_eqj_());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_astronomyengine_astro_angle_from_sun_",              (DL_FUNC) &_astronomyengine_astro_angle_from_sun_,              2},
    {"_astronomyengine_astro_bary_state_",                  (DL_FUNC) &_astronomyengine_astro_bary_state_,                  2},
    {"_astronomyengine_astro_body_code_",                   (DL_FUNC) &_astronomyengine_astro_body_code_,                   1},
    {"_astronomyengine_astro_body_name_",                   (DL_FUNC) &_astronomyengine_astro_body_name_,                   1},
    {"_astronomyengine_astro_combine_rotation_",            (DL_FUNC) &_astronomyengine_astro_combine_rotation_,            2},
    {"_astronomyengine_astro_constellation_",               (DL_FUNC) &_astronomyengine_astro_constellation_,               2},
    {"_astronomyengine_astro_current_time_",                (DL_FUNC) &_astronomyengine_astro_current_time_,                0},
    {"_astronomyengine_astro_ecliptic_",                    (DL_FUNC) &_astronomyengine_astro_ecliptic_,                    4},
    {"_astronomyengine_astro_ecliptic_longitude_",          (DL_FUNC) &_astronomyengine_astro_ecliptic_longitude_,          2},
    {"_astronomyengine_astro_elongation_",                  (DL_FUNC) &_astronomyengine_astro_elongation_,                  2},
    {"_astronomyengine_astro_equator_",                     (DL_FUNC) &_astronomyengine_astro_equator_,                     7},
    {"_astronomyengine_astro_equator_from_vector_",         (DL_FUNC) &_astronomyengine_astro_equator_from_vector_,         1},
    {"_astronomyengine_astro_geo_vector_",                  (DL_FUNC) &_astronomyengine_astro_geo_vector_,                  3},
    {"_astronomyengine_astro_helio_distance_",              (DL_FUNC) &_astronomyengine_astro_helio_distance_,              2},
    {"_astronomyengine_astro_helio_vector_",                (DL_FUNC) &_astronomyengine_astro_helio_vector_,                2},
    {"_astronomyengine_astro_horizon_",                     (DL_FUNC) &_astronomyengine_astro_horizon_,                     6},
    {"_astronomyengine_astro_horizon_from_vector_",         (DL_FUNC) &_astronomyengine_astro_horizon_from_vector_,         2},
    {"_astronomyengine_astro_hour_angle_",                  (DL_FUNC) &_astronomyengine_astro_hour_angle_,                  5},
    {"_astronomyengine_astro_identity_matrix_",             (DL_FUNC) &_astronomyengine_astro_identity_matrix_,             0},
    {"_astronomyengine_astro_illumination_",                (DL_FUNC) &_astronomyengine_astro_illumination_,                2},
    {"_astronomyengine_astro_inverse_rotation_",            (DL_FUNC) &_astronomyengine_astro_inverse_rotation_,            1},
    {"_astronomyengine_astro_make_time_",                   (DL_FUNC) &_astronomyengine_astro_make_time_,                   6},
    {"_astronomyengine_astro_moon_phase_",                  (DL_FUNC) &_astronomyengine_astro_moon_phase_,                  1},
    {"_astronomyengine_astro_next_lunar_eclipse_",          (DL_FUNC) &_astronomyengine_astro_next_lunar_eclipse_,          1},
    {"_astronomyengine_astro_next_moon_quarter_",           (DL_FUNC) &_astronomyengine_astro_next_moon_quarter_,           2},
    {"_astronomyengine_astro_next_transit_",                (DL_FUNC) &_astronomyengine_astro_next_transit_,                2},
    {"_astronomyengine_astro_observer_gravity_",            (DL_FUNC) &_astronomyengine_astro_observer_gravity_,            2},
    {"_astronomyengine_astro_observer_state_",              (DL_FUNC) &_astronomyengine_astro_observer_state_,              5},
    {"_astronomyengine_astro_observer_vector_",             (DL_FUNC) &_astronomyengine_astro_observer_vector_,             5},
    {"_astronomyengine_astro_pair_longitude_",              (DL_FUNC) &_astronomyengine_astro_pair_longitude_,              3},
    {"_astronomyengine_astro_pivot_",                       (DL_FUNC) &_astronomyengine_astro_pivot_,                       3},
    {"_astronomyengine_astro_rotate_vector_",               (DL_FUNC) &_astronomyengine_astro_rotate_vector_,               2},
    {"_astronomyengine_astro_rotation_ecl_eqd_",            (DL_FUNC) &_astronomyengine_astro_rotation_ecl_eqd_,            1},
    {"_astronomyengine_astro_rotation_ecl_eqj_",            (DL_FUNC) &_astronomyengine_astro_rotation_ecl_eqj_,            0},
    {"_astronomyengine_astro_rotation_ecl_hor_",            (DL_FUNC) &_astronomyengine_astro_rotation_ecl_hor_,            4},
    {"_astronomyengine_astro_rotation_ect_eqd_",            (DL_FUNC) &_astronomyengine_astro_rotation_ect_eqd_,            1},
    {"_astronomyengine_astro_rotation_ect_eqj_",            (DL_FUNC) &_astronomyengine_astro_rotation_ect_eqj_,            1},
    {"_astronomyengine_astro_rotation_eqd_ecl_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqd_ecl_,            1},
    {"_astronomyengine_astro_rotation_eqd_ect_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqd_ect_,            1},
    {"_astronomyengine_astro_rotation_eqd_eqj_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqd_eqj_,            1},
    {"_astronomyengine_astro_rotation_eqd_hor_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqd_hor_,            4},
    {"_astronomyengine_astro_rotation_eqj_ecl_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqj_ecl_,            0},
    {"_astronomyengine_astro_rotation_eqj_ect_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqj_ect_,            1},
    {"_astronomyengine_astro_rotation_eqj_eqd_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqj_eqd_,            1},
    {"_astronomyengine_astro_rotation_eqj_gal_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqj_gal_,            0},
    {"_astronomyengine_astro_rotation_eqj_hor_",            (DL_FUNC) &_astronomyengine_astro_rotation_eqj_hor_,            4},
    {"_astronomyengine_astro_rotation_gal_eqj_",            (DL_FUNC) &_astronomyengine_astro_rotation_gal_eqj_,            0},
    {"_astronomyengine_astro_rotation_hor_ecl_",            (DL_FUNC) &_astronomyengine_astro_rotation_hor_ecl_,            4},
    {"_astronomyengine_astro_rotation_hor_eqd_",            (DL_FUNC) &_astronomyengine_astro_rotation_hor_eqd_,            4},
    {"_astronomyengine_astro_rotation_hor_eqj_",            (DL_FUNC) &_astronomyengine_astro_rotation_hor_eqj_,            4},
    {"_astronomyengine_astro_search_altitude_",             (DL_FUNC) &_astronomyengine_astro_search_altitude_,             8},
    {"_astronomyengine_astro_search_global_solar_eclipse_", (DL_FUNC) &_astronomyengine_astro_search_global_solar_eclipse_, 1},
    {"_astronomyengine_astro_search_hour_angle_ex_",        (DL_FUNC) &_astronomyengine_astro_search_hour_angle_ex_,        7},
    {"_astronomyengine_astro_search_lunar_apsis_",          (DL_FUNC) &_astronomyengine_astro_search_lunar_apsis_,          1},
    {"_astronomyengine_astro_search_lunar_eclipse_",        (DL_FUNC) &_astronomyengine_astro_search_lunar_eclipse_,        1},
    {"_astronomyengine_astro_search_max_elongation_",       (DL_FUNC) &_astronomyengine_astro_search_max_elongation_,       2},
    {"_astronomyengine_astro_search_moon_phase_",           (DL_FUNC) &_astronomyengine_astro_search_moon_phase_,           3},
    {"_astronomyengine_astro_search_moon_quarter_",         (DL_FUNC) &_astronomyengine_astro_search_moon_quarter_,         1},
    {"_astronomyengine_astro_search_peak_magnitude_",       (DL_FUNC) &_astronomyengine_astro_search_peak_magnitude_,       2},
    {"_astronomyengine_astro_search_relative_longitude_",   (DL_FUNC) &_astronomyengine_astro_search_relative_longitude_,   3},
    {"_astronomyengine_astro_search_rise_set_ex_",          (DL_FUNC) &_astronomyengine_astro_search_rise_set_ex_,          8},
    {"_astronomyengine_astro_search_sun_longitude_",        (DL_FUNC) &_astronomyengine_astro_search_sun_longitude_,        3},
    {"_astronomyengine_astro_search_transit_",              (DL_FUNC) &_astronomyengine_astro_search_transit_,              2},
    {"_astronomyengine_astro_seasons_",                     (DL_FUNC) &_astronomyengine_astro_seasons_,                     1},
    {"_astronomyengine_astro_sphere_from_vector_",          (DL_FUNC) &_astronomyengine_astro_sphere_from_vector_,          1},
    {"_astronomyengine_astro_sun_position_",                (DL_FUNC) &_astronomyengine_astro_sun_position_,                1},
    {"_astronomyengine_astro_vector_from_horizon_",         (DL_FUNC) &_astronomyengine_astro_vector_from_horizon_,         3},
    {"_astronomyengine_astro_vector_from_sphere_",          (DL_FUNC) &_astronomyengine_astro_vector_from_sphere_,          2},
    {"_astronomyengine_astro_vector_observer_",             (DL_FUNC) &_astronomyengine_astro_vector_observer_,             2},
    {"_astronomyengine_next_global_solar_eclipse_",         (DL_FUNC) &_astronomyengine_next_global_solar_eclipse_,         1},
    {"_astronomyengine_next_local_solar_eclipse_",          (DL_FUNC) &_astronomyengine_next_local_solar_eclipse_,          3},
    {"_astronomyengine_next_lunar_apsis_",                  (DL_FUNC) &_astronomyengine_next_lunar_apsis_,                  1},
    {"_astronomyengine_next_planet_apsis_",                 (DL_FUNC) &_astronomyengine_next_planet_apsis_,                 2},
    {"_astronomyengine_search_global_solar_eclipse_",       (DL_FUNC) &_astronomyengine_search_global_solar_eclipse_,       1},
    {"_astronomyengine_search_local_solar_eclipse_",        (DL_FUNC) &_astronomyengine_search_local_solar_eclipse_,        3},
    {"_astronomyengine_search_lunar_apsis_",                (DL_FUNC) &_astronomyengine_search_lunar_apsis_,                1},
    {"_astronomyengine_search_planet_apsis_",               (DL_FUNC) &_astronomyengine_search_planet_apsis_,               2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_astronomyengine(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
