# Generated by cpp11: do not edit by hand

astro_make_time_ <- function(year, month, day, hour, minute, second) {
  .Call(`_astronomyengine_astro_make_time_`, year, month, day, hour, minute, second)
}

astro_current_time_ <- function() {
  .Call(`_astronomyengine_astro_current_time_`)
}

astro_body_name_ <- function(body) {
  .Call(`_astronomyengine_astro_body_name_`, body)
}

astro_body_code_ <- function(name) {
  .Call(`_astronomyengine_astro_body_code_`, name)
}

astro_helio_vector_ <- function(body, time_posix) {
  .Call(`_astronomyengine_astro_helio_vector_`, body, time_posix)
}

astro_equator_ <- function(body, time_posix, latitude, longitude, height, of_date, aberration) {
  .Call(`_astronomyengine_astro_equator_`, body, time_posix, latitude, longitude, height, of_date, aberration)
}

astro_sun_position_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_sun_position_`, time_posix)
}

astro_ecliptic_ <- function(x, y, z, time_posix) {
  .Call(`_astronomyengine_astro_ecliptic_`, x, y, z, time_posix)
}

astro_ecliptic_longitude_ <- function(body, time_posix) {
  .Call(`_astronomyengine_astro_ecliptic_longitude_`, body, time_posix)
}

astro_horizon_ <- function(time_posix, lat, lon, ra, dec, refraction) {
  .Call(`_astronomyengine_astro_horizon_`, time_posix, lat, lon, ra, dec, refraction)
}

astro_pair_longitude_ <- function(body1, body2, time_posix) {
  .Call(`_astronomyengine_astro_pair_longitude_`, body1, body2, time_posix)
}

astro_geo_vector_ <- function(body, time_posix, aberration) {
  .Call(`_astronomyengine_astro_geo_vector_`, body, time_posix, aberration)
}

astro_bary_state_ <- function(body, time_posix) {
  .Call(`_astronomyengine_astro_bary_state_`, body, time_posix)
}

astro_observer_vector_ <- function(time_posix, latitude, longitude, height, of_date) {
  .Call(`_astronomyengine_astro_observer_vector_`, time_posix, latitude, longitude, height, of_date)
}

astro_observer_state_ <- function(time_posix, latitude, longitude, height, of_date) {
  .Call(`_astronomyengine_astro_observer_state_`, time_posix, latitude, longitude, height, of_date)
}

astro_vector_observer_ <- function(vector, of_date) {
  .Call(`_astronomyengine_astro_vector_observer_`, vector, of_date)
}

astro_observer_gravity_ <- function(latitude, height) {
  .Call(`_astronomyengine_astro_observer_gravity_`, latitude, height)
}

astro_search_rise_set_ex_ <- function(body, latitude, longitude, height, time_posix, direction, limit_days, meters_above_ground) {
  .Call(`_astronomyengine_astro_search_rise_set_ex_`, body, latitude, longitude, height, time_posix, direction, limit_days, meters_above_ground)
}

astro_search_altitude_ <- function(body, latitude, longitude, height, time_posix, direction, limit_days, altitude) {
  .Call(`_astronomyengine_astro_search_altitude_`, body, latitude, longitude, height, time_posix, direction, limit_days, altitude)
}

astro_search_hour_angle_ex_ <- function(body, latitude, longitude, height, hour_angle, time_posix, direction) {
  .Call(`_astronomyengine_astro_search_hour_angle_ex_`, body, latitude, longitude, height, hour_angle, time_posix, direction)
}

astro_hour_angle_ <- function(body, latitude, longitude, height, time_posix) {
  .Call(`_astronomyengine_astro_hour_angle_`, body, latitude, longitude, height, time_posix)
}

astro_moon_phase_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_moon_phase_`, time_posix)
}

astro_search_moon_phase_ <- function(target_lon, start_time_posix, limit_days) {
  .Call(`_astronomyengine_astro_search_moon_phase_`, target_lon, start_time_posix, limit_days)
}

astro_search_moon_quarter_ <- function(start_time_posix) {
  .Call(`_astronomyengine_astro_search_moon_quarter_`, start_time_posix)
}

astro_next_moon_quarter_ <- function(quarter, time_posix) {
  .Call(`_astronomyengine_astro_next_moon_quarter_`, quarter, time_posix)
}

astro_search_lunar_eclipse_ <- function(start_time_posix) {
  .Call(`_astronomyengine_astro_search_lunar_eclipse_`, start_time_posix)
}

astro_next_lunar_eclipse_ <- function(prev_eclipse_time_posix) {
  .Call(`_astronomyengine_astro_next_lunar_eclipse_`, prev_eclipse_time_posix)
}

search_global_solar_eclipse_ <- function(start_time) {
  .Call(`_astronomyengine_search_global_solar_eclipse_`, start_time)
}

next_global_solar_eclipse_ <- function(prev_eclipse_time) {
  .Call(`_astronomyengine_next_global_solar_eclipse_`, prev_eclipse_time)
}

search_local_solar_eclipse_ <- function(start_time, latitude, longitude) {
  .Call(`_astronomyengine_search_local_solar_eclipse_`, start_time, latitude, longitude)
}

next_local_solar_eclipse_ <- function(prev_eclipse_time, latitude, longitude) {
  .Call(`_astronomyengine_next_local_solar_eclipse_`, prev_eclipse_time, latitude, longitude)
}

astro_search_transit_ <- function(body, start_time_posix) {
  .Call(`_astronomyengine_astro_search_transit_`, body, start_time_posix)
}

astro_next_transit_ <- function(body, prev_transit_time_posix) {
  .Call(`_astronomyengine_astro_next_transit_`, body, prev_transit_time_posix)
}

search_lunar_apsis_ <- function(start_time) {
  .Call(`_astronomyengine_search_lunar_apsis_`, start_time)
}

next_lunar_apsis_ <- function(apsis_list) {
  .Call(`_astronomyengine_next_lunar_apsis_`, apsis_list)
}

search_planet_apsis_ <- function(body, start_time) {
  .Call(`_astronomyengine_search_planet_apsis_`, body, start_time)
}

next_planet_apsis_ <- function(body, apsis_list) {
  .Call(`_astronomyengine_next_planet_apsis_`, body, apsis_list)
}

astro_illumination_ <- function(body, time_posix) {
  .Call(`_astronomyengine_astro_illumination_`, body, time_posix)
}

astro_search_peak_magnitude_ <- function(body, start_time) {
  .Call(`_astronomyengine_astro_search_peak_magnitude_`, body, start_time)
}

astro_angle_from_sun_ <- function(body, time) {
  .Call(`_astronomyengine_astro_angle_from_sun_`, body, time)
}

astro_elongation_ <- function(body, time) {
  .Call(`_astronomyengine_astro_elongation_`, body, time)
}

astro_search_max_elongation_ <- function(body, start_time) {
  .Call(`_astronomyengine_astro_search_max_elongation_`, body, start_time)
}

astro_search_relative_longitude_ <- function(body, target_rel_lon, start_time) {
  .Call(`_astronomyengine_astro_search_relative_longitude_`, body, target_rel_lon, start_time)
}

astro_search_sun_longitude_ <- function(target_lon, start_time, limit_days) {
  .Call(`_astronomyengine_astro_search_sun_longitude_`, target_lon, start_time, limit_days)
}

astro_seasons_ <- function(year) {
  .Call(`_astronomyengine_astro_seasons_`, year)
}

astro_search_lunar_apsis_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_search_lunar_apsis_`, time_posix)
}

astro_constellation_ <- function(ra, dec) {
  .Call(`_astronomyengine_astro_constellation_`, ra, dec)
}

astro_helio_distance_ <- function(body, time_posix) {
  .Call(`_astronomyengine_astro_helio_distance_`, body, time_posix)
}

astro_search_global_solar_eclipse_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_search_global_solar_eclipse_`, time_posix)
}

astro_identity_matrix_ <- function() {
  .Call(`_astronomyengine_astro_identity_matrix_`)
}

astro_inverse_rotation_ <- function(rotation) {
  .Call(`_astronomyengine_astro_inverse_rotation_`, rotation)
}

astro_combine_rotation_ <- function(a, b) {
  .Call(`_astronomyengine_astro_combine_rotation_`, a, b)
}

astro_pivot_ <- function(rotation, axis, angle) {
  .Call(`_astronomyengine_astro_pivot_`, rotation, axis, angle)
}

astro_rotate_vector_ <- function(rotation, vector) {
  .Call(`_astronomyengine_astro_rotate_vector_`, rotation, vector)
}

astro_vector_from_sphere_ <- function(sphere, time_posix) {
  .Call(`_astronomyengine_astro_vector_from_sphere_`, sphere, time_posix)
}

astro_sphere_from_vector_ <- function(vector) {
  .Call(`_astronomyengine_astro_sphere_from_vector_`, vector)
}

astro_equator_from_vector_ <- function(vector) {
  .Call(`_astronomyengine_astro_equator_from_vector_`, vector)
}

astro_vector_from_horizon_ <- function(sphere, time_posix, refraction) {
  .Call(`_astronomyengine_astro_vector_from_horizon_`, sphere, time_posix, refraction)
}

astro_horizon_from_vector_ <- function(vector, refraction) {
  .Call(`_astronomyengine_astro_horizon_from_vector_`, vector, refraction)
}

astro_rotation_eqd_eqj_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_eqd_eqj_`, time_posix)
}

astro_rotation_eqd_ect_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_eqd_ect_`, time_posix)
}

astro_rotation_eqd_ecl_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_eqd_ecl_`, time_posix)
}

astro_rotation_eqd_hor_ <- function(time_posix, latitude, longitude, height) {
  .Call(`_astronomyengine_astro_rotation_eqd_hor_`, time_posix, latitude, longitude, height)
}

astro_rotation_eqj_eqd_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_eqj_eqd_`, time_posix)
}

astro_rotation_eqj_ect_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_eqj_ect_`, time_posix)
}

astro_rotation_eqj_ecl_ <- function() {
  .Call(`_astronomyengine_astro_rotation_eqj_ecl_`)
}

astro_rotation_eqj_hor_ <- function(time_posix, latitude, longitude, height) {
  .Call(`_astronomyengine_astro_rotation_eqj_hor_`, time_posix, latitude, longitude, height)
}

astro_rotation_ect_eqd_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_ect_eqd_`, time_posix)
}

astro_rotation_ect_eqj_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_ect_eqj_`, time_posix)
}

astro_rotation_ecl_eqd_ <- function(time_posix) {
  .Call(`_astronomyengine_astro_rotation_ecl_eqd_`, time_posix)
}

astro_rotation_ecl_eqj_ <- function() {
  .Call(`_astronomyengine_astro_rotation_ecl_eqj_`)
}

astro_rotation_ecl_hor_ <- function(time_posix, latitude, longitude, height) {
  .Call(`_astronomyengine_astro_rotation_ecl_hor_`, time_posix, latitude, longitude, height)
}

astro_rotation_hor_eqd_ <- function(time_posix, latitude, longitude, height) {
  .Call(`_astronomyengine_astro_rotation_hor_eqd_`, time_posix, latitude, longitude, height)
}

astro_rotation_hor_eqj_ <- function(time_posix, latitude, longitude, height) {
  .Call(`_astronomyengine_astro_rotation_hor_eqj_`, time_posix, latitude, longitude, height)
}

astro_rotation_hor_ecl_ <- function(time_posix, latitude, longitude, height) {
  .Call(`_astronomyengine_astro_rotation_hor_ecl_`, time_posix, latitude, longitude, height)
}

astro_rotation_eqj_gal_ <- function() {
  .Call(`_astronomyengine_astro_rotation_eqj_gal_`)
}

astro_rotation_gal_eqj_ <- function() {
  .Call(`_astronomyengine_astro_rotation_gal_eqj_`)
}
